CREATE DATABASE IF NOT EXISTS gb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gb;
CREATE TABLE units(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),number VARCHAR(30) UNIQUE,owner_name VARCHAR(100),owner_phone VARCHAR(30),service_fee DECIMAL(12,0) DEFAULT 0);
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(100) UNIQUE,password VARCHAR(255),role VARCHAR(20) DEFAULT 'resident',permissions VARCHAR(255) DEFAULT '',unit_id INT NULL,FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE SET NULL);
CREATE TABLE vehicles(id INT AUTO_INCREMENT PRIMARY KEY,unit_id INT,plate VARCHAR(30),type VARCHAR(50),FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE CASCADE);
CREATE TABLE invoices(id INT AUTO_INCREMENT PRIMARY KEY,unit_id INT,type ENUM('electricity','gas','service'),amount DECIMAL(12,0),due_date DATE,period CHAR(7),FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE CASCADE);
CREATE TABLE payments(id INT AUTO_INCREMENT PRIMARY KEY,invoice_id INT,unit_id INT,amount DECIMAL(12,0),received_by INT NULL,paid_at DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(invoice_id) REFERENCES invoices(id) ON DELETE CASCADE);
